source "http://rubygems.org"

gem "sinatra"
gem "sinatra-sequel"
gem "sqlite3"
gem "state_machine"
gem "thin"
gem "haml"
gem "juggernaut"
gem "json"
gem "rubyvor"
gem "watir-webdriver"
gem "pry"
gem "SystemTimer"
